service: sendshit
provider:
  name: aws
  runtime: go1.x
  region: ${file(./.env.yml):REGION, env:REGION}
  memorySize: 128
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - s3:PutObject
        - s3:GetObject
      Resource: "arn:aws:s3:::${file(./.env.yml):FILE_BUCKET, env:FILE_BUCKET}/*"
package:
 exclude:
   - ./**
 include:
   - ./server/bin/**
plugins:
  - serverless-finch
functions:
  server:
    handler: server/bin/server
    description: Sendsh.it File Transfer
    environment:
      REGION: ${file(./.env.yml):REGION, env:REGION}
      BUCKET: ${file(./.env.yml):FILE_BUCKET, env:FILE_BUCKET}
    events:
      - http:
          method: any
          path: /api/{proxy+}
resources:
  Resources:
    ProxyResource:
      Type: AWS::ApiGateway::Resource
      Properties:
        ParentId:
          Fn::GetAtt:
            - ApiGatewayRestApi
            - RootResourceId
        PathPart: '{proxy+}'
        RestApiId:
          Ref: ApiGatewayRestApi
    ProxyMethod:
      Type: AWS::ApiGateway::Method
      Properties:
        ResourceId:
          Ref: ProxyResource
        RestApiId:
          Ref: ApiGatewayRestApi
        AuthorizationType: NONE
        HttpMethod: GET
        MethodResponses:
          - StatusCode: 200
        Integration:
          IntegrationHttpMethod: GET
          Type: HTTP_PROXY
          Uri: 'http://${file(./.env.yml):CLIENT_BUCKET, env:CLIENT_BUCKET}.s3-website-${file(./.env.yml):REGION, env:REGION}.amazonaws.com/{proxy}'
          PassthroughBehavior: WHEN_NO_MATCH
          IntegrationResponses:
            - StatusCode: 200
custom:
  client:
    bucketName: ${file(./.env.yml):CLIENT_BUCKET, env:CLIENT_BUCKET}
    distributionFolder: client/build
    indexDocument: index.html
    errorDocument: index.html
