service: sendshit
provider:
  name: aws
  runtime: go1.x
  region: eu-west-1
  memorySize: 128
package:
 exclude:
   - ./**
 include:
   - ./server/bin/**
plugins:
  - serverless-finch
functions:
  server:
    handler: server/bin/server
    description: Sendsh.it File Transfer
    #role: arn:aws:iam::068310699258:role/sendshitLambdaRole
    environment:
      REGION: eu-west-1
      BUCKET: sendsh.it
    events:
      - http:
          method: any
          path: /api/{proxy+}
          cors: true
resources:
  Resources:
    ProxyResource:
      Type: AWS::ApiGateway::Resource
      Properties:
        ParentId:
          Fn::GetAtt:
            - ApiGatewayRestApi
            - RootResourceId
        PathPart: '{proxy+}'
        RestApiId:
          Ref: ApiGatewayRestApi
    ProxyMethod:
      Type: AWS::ApiGateway::Method
      Properties:
        ResourceId:
          Ref: ProxyResource
        RestApiId:
          Ref: ApiGatewayRestApi
        AuthorizationType: NONE
        HttpMethod: GET
        MethodResponses:
          - StatusCode: 200
        Integration:
          IntegrationHttpMethod: GET
          Type: HTTP_PROXY
          Uri: 'http://sendsh.it-frontend.s3-website-eu-west-1.amazonaws.com/{proxy}'
          PassthroughBehavior: WHEN_NO_MATCH
          IntegrationResponses:
            - StatusCode: 200
custom:
  client:
    bucketName: sendsh.it-frontend
    distributionFolder: client/build
    indexDocument: index.html
    errorDocument: index.html
